// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "tamp-20190121124834-hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://tamp-20190121124834-hostingbucket.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:3d591c68-890d-4a0f-b0f3-bd93876fc1b7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_aLuVrlbaE",
    "aws_user_pools_web_client_id": "7snr1hf628mseen9rbk094iabo"
};


export default awsmobile;
